# Generated by Django 3.0.2 on 2020-09-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
